### PR TITLE
Chore: improve hello example apps (example/js)

### PR DESCRIPTION
**Pull request by D4ryl00**
This PR moves the `hello` example app using Expo from `example/js/react-native/hello` to `example/js/expo/hello`, and modifies the `new-app` Makefile rule to create new apps in the new `example/js/expo` directory.

We also recreate `example/js/react-native/hello` from scratch following the react-native guide, to create a new `hello` app without Expo. Then we integrated gnonative files without the gnonative NPM package. The steps to accomplish that are written in the `example/js/react-native/hello/README.md` file so anyone can integrate gnonative in its bare React-Native app.

### CODE REVIEW

**Comment by jefft0** [comment]
I try `new-app` as follows:
```
APP_NAME=newapp make new-app
cd examples/js/expo/newapp
yarn start
```
Then in Xcode, open and run examples/js/expo/newapp/ios/newapp.xcworkspace . Metro prints:
```
 ERROR  Error: Cannot find native module 'Gnonative', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by jefft0** [comment]
In gnoboard, [this line](https://github.com/D4ryl00/gnonative/blob/1175fe0ee493895469ad613b049d2cfe0af6282a/examples/js/react-native/gnoboard/src/screens/remove-account/index.tsx#L13) should be
```
const { gnonative } = useGnoNativeContext();
```
the same [as here](https://github.com/D4ryl00/gnonative/blob/1175fe0ee493895469ad613b049d2cfe0af6282a/examples/js/react-native/gnoboard/src/screens/switch-accounts/index.tsx#L14). (I don't know if you want to fix it in this PR or a future PR.)

**Comment by D4ryl00** [comment]
> I try `new-app` as follows:
> 
> ```
> APP_NAME=newapp make new-app
> cd examples/js/expo/newapp
> npm start
> ```
> 
> Then in Xcode, open and run examples/js/expo/newapp/ios/newapp.xcworkspace . Metro prints:
> 
> ```
>  ERROR  Error: Cannot find native module 'Gnonative', js engine: hermes
>  ERROR  Invariant Violation: "main" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
> ```

Is it still valid? I've tried that in a fresh clone and that works fine.

**Comment by D4ryl00** [comment]
> In gnoboard, [this line](https://github.com/D4ryl00/gnonative/blob/1175fe0ee493895469ad613b049d2cfe0af6282a/examples/js/react-native/gnoboard/src/screens/remove-account/index.tsx#L13) should be
> 
> ```
> const { gnonative } = useGnoNativeContext();
> ```
> 
> the same [as here](https://github.com/D4ryl00/gnonative/blob/1175fe0ee493895469ad613b049d2cfe0af6282a/examples/js/react-native/gnoboard/src/screens/switch-accounts/index.tsx#L14). (I don't know if you want to fix it in this PR or a future PR.)

fixed

**Comment by jefft0** [comment]
> Is it still valid? I've tried that in a fresh clone and that works fine.

Still getting the error.

image

image

**Pull request merged**
