### PR TITLE
chore: centralize API usage

### PR DESCRIPTION
**Pull request by D4ryl00**
This PR wants all the example apps and the Go framework to use the API in the `./api` folder instead of copying the API files into their subdirectory. So if you update the API files, every app will use the latest version of them.

Fixes https://github.com/gnolang/gnonative/issues/103

### CODE REVIEW

**Review by iuricmp — APPROVED** [review]
I didn't run this branch, but looks good to me.

**Comment by jefft0** [comment]
... The same error for Android. I do `make build.android`. I open and run the gnoboard Android project. When the app starts it prints:
```
Android Bundling failed 1278ms
Unable to resolve "@bufbuild/protobuf" from "../../../api/gen/es/rpc_pb.js"
```

**Comment by jefft0** [comment]
Problem with Wails. In a fresh clone of this branch, I go to `examples/wails` and follow the new README (including patch files). `wails dev` prints:
```
    src/hooks/use-gno.ts(36,25): error TS2307: Cannot find module '@gno/api/gnonativetypes_pb' or its corresponding type declarations.
```

**Comment by jefft0** [comment]
Problem with new-app. In a fresh clone, I enter `APP_NAME=myapp make new-app`. It prints:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make new-react-native-app OUTPUT_DIR=/Users/jefft0/temp/gnonative/examples/react-native
creating a new gno awesome project at: /Users/jefft0/temp/gnonative/examples/react-native
cd /Users/jefft0/temp/gnonative/examples/react-native && yarn create expo gnoboard --template expo-template-blank-typescript
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-expo@2.1.4" with binaries:
      - create-expo
[##] 2/2The directory gnoboard has files that might be overwritten:

  .eslintrc.json
  .prettierignore
  .prettierrc
  .storybook
  App.tsx
  Makefile
  REAME.md
  android
  app.json
  assets
  babel.config.js
  ios
  metro.config.js
  package.json
  src
  tsconfig.json
  yarn.lock

Try using a new directory name, or moving these files.

error Command failed.
Exit code: 1
Command: /Users/jefft0/.yarn/bin/create-expo
Arguments: gnoboard --template expo-template-blank-typescript
Directory: /Users/jefft0/temp/gnonative/examples/react-native
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
make[1]: *** [new-react-native-app] Error 1
make: *** [new-app] Error 2
```

**Comment by jefft0** [comment]
The problems with gnoboard mentioned above are resolved.
Still a (different) problem with Wails. I followed the new README. `wails dev` prints:
```
    vite v3.2.8 building for production...
    transforming...
    ✓ 22 modules transformed.

    [vite]: Rollup failed to resolve import "@bufbuild/protobuf" from "../../../../api/gen/es/rpc_connect.js".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
    error during build:
    Error: [vite]: Rollup failed to resolve import "@bufbuild/protobuf" from "../../../../api/gen/es/rpc_connect.js".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
        at onRollupWarning (file:///Users/jefft0/temp/gnonative/examples/wails/myproject/frontend/node_modules/vite/dist/node/chunks/dep-f11f7337.js:45909:19)
        at onwarn (file:///Users/jefft0/temp/gnonative/examples/wails/myproject/frontend/node_modules/vite/dist/node/chunks/dep-f11f7337.js:45680:13)
        at Object.onwarn (file:///Users/jefft0/temp/gnonative/examples/wails/myproject/frontend/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
        at ModuleLoader.handleResolveId (file:///Users/jefft0/temp/gnonative/examples/wails/myproject/frontend/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
        at file:///Users/jefft0/temp/gnonative/examples/wails/myproject/frontend/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```

**Comment by jefft0** [comment]
The problem with `make new-app` with iOS is resolved.

**Review by jefft0 — APPROVED** [review]
Tested `make new-app`, the Wails example and the gnoboard example on Android and iOS simulators.

**Pull request merged**
